{% set name = "pyaerocom" %}
{% set version = "0.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32ea2abdf117975b8b4543da17c4997aba10886fa00a9d4fe7dd054705aa2d6f

build:
  number: 0
  entry_points:
    - pyaeroeval=pyaerocom.web.cli.main_aerocom_evaluation:main
    - pyaerotrends=pyaerocom.web.cli.main_trends_evaluation:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - iris >=2.1.0, <3.0.0
    - xarray >=0.16.0
    - cartopy >=0.16.0
    - matplotlib >=3.1.1
    - scipy >=1.3.1
    - pandas >=0.23.0, <=1.2.2
    - seaborn >=0.8.0
    - geonum
    - numpy
    - simplejson
    - requests
    - reverse-geocode
    - tqdm

test:
  imports:
    - pyaerocom
  requires:
    - pytest
  commands:
    - py.test --pyargs pyaerocom

about:
  home: https://github.com/metno/pyaerocom.git
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python tools for the AeroCom project
  doc_url: https://pyaerocom.readthedocs.io/en/latest/
  dev_url: https://github.com/metno/pyaerocom

extra:
  recipe-maintainers:
    - jgriesfeller
    - avaldebe
    - jgliss