{% set version = "0.13.1.post1" %}

package:
  name: pyaerocom
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyaerocom/pyaerocom-{{ version }}.tar.gz
  sha256: cb0cc3930ddf10472d7a8f8d244f04ddea8633aa3d244bd4d4c0dbd568ccdf96

build:
  number: 0
  entry_points:
    - pya=pyaerocom.scripts.cli:main
  noarch: python
  script: "pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - iris >=3.2.0
    - xarray >=0.16.0
    - cartopy >=0.20.0
    - matplotlib-base >=3.0.1
    - scipy >=1.1.0
    - pandas >=1.3.0
    - numpy >=0.12.0
    - seaborn >=0.8.0
    - dask
    - geonum
    - numpy
    - simplejson
    - requests
    - reverse-geocode
    - tqdm
    - openpyxl
    - typer >=0.4.0

test:
  imports:
    - pyaerocom
  source_files:
    - tests
  requires:
    - pytest>=6.0
    - pytest-dependency
    - pytest-cov
    - packaging
  commands:
    - pytest tests/

about:
  home: https://github.com/metno/pyaerocom.git
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python tools for the AeroCom project
  doc_url: https://pyaerocom.readthedocs.io/en/latest/
  dev_url: https://github.com/metno/pyaerocom

extra:
  recipe-maintainers:
    - avaldebe
    - jgliss
    - jgriesfeller
    - dulte
