{% set name = "pyaerocom" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 555a4b4ccd26a0facee6f4303bcf95db4fcfd830fd717ab321083099e632ffd4

build:
  number: 0
  entry_points:
    - pyaeroeval=pyaerocom.web.cli.main_aerocom_evaluation:main
    - pyaerotrends=pyaerocom.web.cli.main_trends_evaluation:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - iris >=2.1.0, <3.1.0
    - xarray >=0.16.0
    - cartopy >=0.16.0
    - matplotlib >=3.0.1
    - scipy >=1.1.0
    - pandas >=0.23.0
    - seaborn >=0.8.0
    - geonum
    - numpy
    - simplejson
    - requests
    - reverse-geocode
    - tqdm
    - openpyxl
    - nbsphinx

test:
  imports:
    - pyaerocom
  requires:
    - pytest
  commands:
    - py.test --pyargs pyaerocom

about:
  home: https://github.com/metno/pyaerocom.git
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python tools for the AeroCom project
  doc_url: https://pyaerocom.readthedocs.io/en/latest/
  dev_url: https://github.com/metno/pyaerocom

extra:
  recipe-maintainers:
    - avaldebe
    - jgliss
    - jgriesfeller
