{% set name = "pyaerocom" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 694ef61878d600e4a05e66d13e4d1493e5156012376b6dac780c72781e47a873

build:
  number: 1
  entry_points:
    - pyaeroeval=pyaerocom.web.cli.main_aerocom_evaluation:main
    - pyaerotrends=pyaerocom.web.cli.main_trends_evaluation:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - iris >=2.1.0
    - xarray >=0.10.8
    - cartopy >=0.16.0
    - matplotlib-base !=3.1.1
    - scipy >=1.3.1
    - pandas >=0.23.0
    - seaborn >=0.8.0
    - netcdf4
    - geonum
    - cf_units
    - numpy
    - simplejson

test:
  imports:
    - pyaerocom
  requires:
    - pytest
  commands:
    - py.test --pyargs pyaerocom

about:
  home: https://github.com/metno/pyaerocom.git
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python tools for the AeroCom project
  doc_url: https://pyaerocom.met.no/
  dev_url: https://github.com/metno/pyaerocom

extra:
  recipe-maintainers:
    - jgliss
